server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/productService
    username: jiash
    password: Asas4545
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

    hibernate:
      ddl-auto: validate
    show-sql: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp